---
title: "R Notebook"
output: html_notebook
---

Interacting with R



```{r}
1+1

help("mean")

mean(c(2, 3))

mean
```

Some math

```{r}
4*5

9/3

6-5


```

Objects

```{r}
weight_kg <- 55

# weight_kg = 55


```

How to name and not to name objects

weigth_kg 

thiswillbetoolongtouse
2weigth

weightKg


Operations with objects

```{r}
2.2 * weight_kg

weight_kg <- 57.5

weight_kg * 2.2

weight_lb <- weight_kg *2.2 

weight_kg <- 100

weight_lb
```

Challenge question

mass <- 47.5            # mass?
age  <- 122             # age?
mass <- mass * 2.0      # mass?
age  <- age - 20        # age?
mass_index <- mass/age  # mass_index?

Functions

```{r}
weight_kg <- sqrt(10)
sqrt()
weight_kg

round(3.14159)
args(round)

round(3.14159, digits = 2)
round(3.14159, 2)

round(digits = 2, 3.14159)
```


Vectors

```{r}

weight_g <- c(50, 60, 65, 82)
weight_g


animals <- c("mouse", "rat", "dog")
animals

length(animals)

length(weight_g)

class(animals)

class(weight_g)

str(animals)

weight_g <- c(weight_g, 90)
weight_g
```

Answering challenge questions

```{r}
num_char <- c(1, 2, 3, "a")
class(num_char)

num_logical <- c(1, 2, 3, TRUE)
class(num_logical)

char_logical <- c("a", "b", "c", TRUE)
class(char_logical)

tricky <- c(1, 2, 3, "4")
class(tricky)

```

Subset vectors

```{r}
animals <- c("mouse", "rat", "dog", "cat")

animals[2]

animals[c(3, 2)]

more_animals <- animals[c(1, 2, 3, 1, 1, 2, 4)]
more_animals

animals[4]

rm(animals)

```

Conditional subsetting

```{r}
weight_g <- c(21,34, 39, 54, 55)

weight_g[c(TRUE, FALSE, FALSE, TRUE, TRUE)]

weight_g >50

weight_g[weight_g >= 50]

weight_g[weight_g >30 | weight_g <= 50]

weight_g[weight_g == 55]
```

Missing values

```{r}
heights <- c(2, 4, 4, NA, 6)

mean(heights, na.rm = F)

args(mean)

heights[!is.na(heights)]


help("mean")

```

































































